Instagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('home.urls', namespace='home')),
    path("profile/", include('users.urls', namespace='users')),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
	path('post/<uuid:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
	path('post/delete/<uuid:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
	path('post/update/<uuid:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
	path('post/create/', views.PostCreateView.as_view(), name='post_create'),
	path('reply/<uuid:post_id>/<uuid:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
	path('edit-comment/<uuid:comment_id>/edit/', views.edit_comment, name='edit-comment'),
	path('like/<uuid:post_id>/', views.PostLikeView.as_view(), name='post_like'),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
	path('register/', views.UserRegisterView.as_view(), name='user_register'),
	path('login/', views.UserLoginView.as_view(), name='user_login'),
	path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
	path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
	path('delete/<int:user_id>/', views.delete_user, name='delete_user'),
	path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
	path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
	path('follow/<uuid:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
	path('unfollow/<uuid:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
	path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
]

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from posts.models import Post, Comment, Like, PostImage, Tag
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from posts.forms import PostCreateUpdateForm, CommentCreateForm, CommentReplyForm, PostSearchForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class HomeView(View):
	form_class = PostSearchForm

	def get(self, request):
		posts = Post.objects.all()
		if request.GET.get('search'):
			posts = posts.filter(content__contains=request.GET['search'])
		return render(request, 'home/index.html', {'posts':posts, 'form':self.form_class})


class PostDetailView(View):
	form_class = CommentCreateForm
	form_class_reply = CommentReplyForm

	def setup(self, request, *args, **kwargs):
		self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'], slug=kwargs['post_slug'])
		return super().setup(request, *args, **kwargs)

	def get(self, request, *args, **kwargs):
		comments = self.post_instance.pcomments.filter(is_reply=False)
		can_like = False
		if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
			can_like = True
		post_images = self.post_instance.postimage_set.all()
		return render(request, 'home/detail.html', {'post':self.post_instance, 'comments':comments, 'form':self.form_class, 'reply_form':self.form_class_reply, 'can_like':can_like})

	@method_decorator(login_required)
	def post(self, request, *args, **kwargs):
		form = CommentCreateForm(request.POST)
		if form.is_valid():
			new_comment = form.save(user=request.user, post=self.post_instance)
			messages.success(request, 'your comment submitted successfully', 'success')
			return redirect('home:post_detail', self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
	def get(self, request, post_id):
		post = get_object_or_404(Post, pk=post_id)
		if post.user.id == request.user.id:
			post.delete()
			messages.success(request, 'post deleted successfully', 'success')
		else:
			messages.error(request, 'you cant delete this post', 'danger')
		return redirect('home:home')


class PostUpdateView(LoginRequiredMixin, View):
	form_class = PostCreateUpdateForm

	def setup(self, request, *args, **kwargs):
		self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'])
		return super().setup(request, *args, **kwargs)

	def dispatch(self, request, *args, **kwargs):
		post = self.post_instance
		if not post.user.id == request.user.id:
			messages.error(request, 'you cant update this post', 'danger')
			return redirect('home:home')
		return super().dispatch(request, *args, **kwargs)

	def get(self, request, *args, **kwargs):
		post = self.post_instance
		form = self.form_class(instance=post)
		return render(request, 'home/update.html', {'form':form})

	def post(self, request, *args, **kwargs):
		post = self.post_instance
		form = self.form_class(request.POST, request.FILES, instance=post)
		if form.is_valid():
			new_post = form.save(commit=False)
			new_post.slug = slugify(form.cleaned_data['content'][:30])
			new_post.save()
			if form.cleaned_data.get('image'):
				for image in request.FILES.getlist('image'):
					PostImage.objects.create(post=new_post, image=image)
			messages.success(request, 'you updated this post', 'success')
			return redirect('home:post_detail', post.id, post.slug)
		else:
			return render(request, 'home/update.html', {'form': form})

class PostCreateView(LoginRequiredMixin, View):
	form_class = PostCreateUpdateForm

	def get(self, request, *args, **kwargs):
		form = self.form_class
		return render(request, 'home/create.html', {'form':form})

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST, request.FILES)
		if form.is_valid():
			new_post = form.save(commit=False)
			new_post.slug = slugify(form.cleaned_data['content'][:30])
			new_post.user = request.user
			new_post.save()
			if form.cleaned_data.get('image'):
				for image in request.FILES.getlist('image'):
					PostImage.objects.create(related_post=new_post, image=image)
			messages.success(request, 'you created a new post', 'success')
			return redirect('home:post_detail', new_post.id, new_post.slug)
		return render(request, 'home/create.html', {'form':form})

class PostAddReplyView(LoginRequiredMixin, View):
	form_class = CommentReplyForm

	def post(self, request, post_id, comment_id):
		post = get_object_or_404(Post, id=post_id)
		comment = get_object_or_404(Comment, id=comment_id)
		form = self.form_class(request.POST)
		if form.is_valid():
			reply = form.save(commit=False)
			reply.user = request.user
			reply.post = post
			reply.reply = comment
			reply.is_reply = True
			reply.save()
			messages.success(request, 'your reply submitted successfully', 'success')
		return redirect('home:post_detail', post.id, post.slug)

@login_required
def edit_comment(request, comment_id):
	comment = Comment.objects.get(id=comment_id)

	if request.method == 'POST':
		new_content = request.POST.get('content')
		try:
			comment.edit_comment(request.user, new_content)
			messages.success(request, 'Comment edited successfully.')
		except (PermissionError, ValueError) as e:
			messages.error(request, str(e))
		return redirect('post-detail', post_id=comment.post.id)

	context = {
		'comment': comment
	}
	return render(request, 'edit_comment.html', context)


class PostLikeView(LoginRequiredMixin, View):
	def get(self, request, post_id):
		post = get_object_or_404(Post, id=post_id)
		like = Like.objects.filter(related_post=post, user=request.user)
		if like.exists():
			messages.error(request, 'you have already liked this post', 'danger')
		else:
			Like.objects.create(related_post=post, user=request.user)
			messages.success(request, 'you liked this post', 'success')
		return redirect('home:post_detail', post.id, post.slug)

home/templates/home/create.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}

    {% if request.user.id == post.user.id %}
        <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">Delete</a>
        <a href="{% url 'home:post_update' post.id %}" class="btn btn-info">Update</a>
    {% endif %}

    <p><a href="{% url 'users:user_profile' post.user.id %}">{{ post.user.username }}</a> - {{ post.updated|date:"Y-M" }}</p>
    <div class="card">
        <img class="slide-item" src="media/uploads/photos/DSC_6768_97qZmyr.jpg" alt="post image">
    </div>
    <p>{{ post.content }}</p><hr/>

    {% if request.user.is_authenticated %}

        <a href="{% url 'home:post_like' post.id %}" class="{% if can_like %}disabled{% endif %} btn btn-primary col-md-2">Like {{ post.likes_count }}</a>

        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form> <br/>
    {% else %}
        <p class="alert alert-danger">Only logged in users can comment.</p>
    {% endif %}

    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-header">{{ comment.user }} | {{ comment.created|timesince }}</p>
            <p class="card-body">{{ comment.content }}</p>
            {% if request.user == comment.user %}
                <a href="{% url 'home:edit-comment' comment.id %}" class="btn btn-secondary">Edit</a>
            {% endif %}

            {% if request.user.is_authenticated %}
                <form action="{% url 'home:add_reply' post.id comment.id %}" method="post" style="display:none;">
                    {% csrf_token %}
                    {{ reply_form.as_p }}
                    <input type="submit" value="send">
                </form>
            {% endif %}

            {% with replies=comment.rcomments.all %}
                {% for reply in replies %}
                    <p class="bg-primary p-3 m-2">{{ reply.user }} <br/> {{ reply.content }}</p>
                {% endfor %}
            {% endwith %}
        </div><br/>
    {% empty %}
        <p>No comments yet!</p>
    {% endfor %}

{% endblock %}

home/templates/home/edit_comment.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit">
    </form>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form><br/><br/>

    <div class="card">
        {% for post in posts %}
            <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.content|truncatewords:8 }}</a>
        {% endfor %}
    </div>
{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}